# Generated by Django 5.1.7 on 2025-03-25 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('jam', models.TimeField(default=django.utils.timezone.now)),
                ('uraian', models.CharField(max_length=255)),
                ('kas_masuk', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('kas_keluar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Cashflow',
                'ordering': ['-tanggal', '-jam'],
            },
        ),
    ]
