# Generated by Django 5.1.7 on 2025-03-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.CharField(max_length=50, unique=True, verbose_name='Nomor Order')),
                ('tgl_jual', models.DateField(verbose_name='Tanggal Jual')),
                ('item_barang', models.CharField(max_length=100, verbose_name='Item Barang')),
                ('qty', models.PositiveIntegerField(verbose_name='Quantity')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='draft', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Penjualan',
                'verbose_name_plural': 'Penjualan',
            },
        ),
    ]
