# Generated by Django 5.1.7 on 2025-03-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan',
            name='orderno',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nomor Order'),
        ),
    ]
