# Generated by Django 5.1.7 on 2025-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='status',
            field=models.CharField(choices=[('anggota', 'Anggota'), ('admin', 'Admin'), ('staf', 'Staf')], default='anggota', max_length=20, verbose_name='Status'),
        ),
    ]
