# Generated by Django 5.1.7 on 2025-04-02 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kolam', '0002_alter_kolam_options_alter_kolam_bahan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Pencatatan')),
                ('suhu', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Suhu Air (°C)')),
                ('kelembaban', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Kelembaban (%)')),
                ('ketinggian_air', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ketinggian Air (cm)')),
                ('ph_air', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='pH Air')),
                ('kualitas_air', models.CharField(choices=[('baik', 'Baik'), ('sedang', 'Sedang'), ('buruk', 'Buruk')], max_length=20, verbose_name='Kualitas Air')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan Tambahan')),
                ('kolamdesc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='kolam.kolam', verbose_name='Kolam')),
            ],
            options={
                'verbose_name': 'Data Sensor IoT',
                'verbose_name_plural': 'Data Sensor IoT',
                'ordering': ['-timestamp'],
            },
        ),
    ]
