# Generated by Django 5.1.7 on 2025-03-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kolam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolam_desc', models.CharField(max_length=100, verbose_name='Deskripsi Kolam')),
                ('bahan', models.CharField(max_length=50, verbose_name='Bahan Kolam')),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Diameter (meter)')),
                ('tinggi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tinggi (meter)')),
                ('kapasitas', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Kapasitas (liter)')),
            ],
            options={
                'verbose_name_plural': 'Daftar Kolam',
            },
        ),
    ]
