# Generated by Django 5.1.7 on 2025-04-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kolam',
            options={},
        ),
        migrations.AlterField(
            model_name='kolam',
            name='bahan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kolam',
            name='diameter',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='kolam',
            name='kapasitas',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='kolam',
            name='kolam_desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kolam',
            name='tinggi',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
