# Generated by Django 5.1.7 on 2025-04-01 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kolam', '0002_alter_kolam_options_alter_kolam_bahan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PemeliharaanKolam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Pemeliharaan')),
                ('uraian_kegiatan', models.TextField(verbose_name='Uraian Kegiatan')),
                ('nilai_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nilai/Nominal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kolamdesc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemeliharaan', to='kolam.kolam', verbose_name='Kolam')),
            ],
            options={
                'verbose_name': 'Pemeliharaan Kolam',
                'verbose_name_plural': 'Daftar Pemeliharaan Kolam',
                'ordering': ['-tanggal'],
            },
        ),
    ]
